# set base image (host OS)
FROM python:3.10-slim-bullseye

# set the working directory in the container
WORKDIR /code

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

# copy the content of the local src directory to the working directory
COPY . .
#RUN mkdir src
#COPY src/ /src/

# command to run on container start
#CMD [ "python", "./app.py" ] 
ENTRYPOINT ["/bin/bash","./entrypoint_dbt_docs.sh"]